apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "gcsfuse-nginx.fullname" . }}
  labels:
    {{- include "gcsfuse-nginx.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "gcsfuse-nginx.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "gcsfuse-nginx.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      volumes:
      - name: sa-volume
        secret:
          secretName: {{ include "gcsfuse-nginx.secretName" . }}
          items:
          - key: sa_json
            path: sa_credentials.json
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
          - name: sa-volume
            mountPath: /etc/gcp
            readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: /etc/gcp/sa_credentials.json
          securityContext:
            privileged: true
            capabilities:
              add:
                - SYS_ADMIN
          lifecycle:
            postStart:
              exec:
                {{ if .Values.gcpFuse.dir }}
                command: ["gcsfuse", "-o", "allow_other", "--only-dir", "{{ .Values.gcpFuse.dir }}", "{{ .Values.gcpFuse.bucket }}", "/usr/share/nginx/html"]
                {{ else }}
                command: ["gcsfuse", "-o", "allow_other", "{{ .Values.gcpFuse.bucket }}", "/usr/share/nginx/html"]
                {{ end }}
            preStop:
              exec:
                command: ["fusermount", "-u", "/usr/share/nginx"]
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
